export default [
  { name: "Grapeseed", shortName: "GS", type: "gs" },
  { name: "Beginner", shortName: "Beg", type: "beg" },
  { name: "Elementary", shortName: "El", type: "el" },
  { name: "Low Intermediate", shortName: "L-Int", type: "lint" },
  { name: "High Intermediate", shortName: "H-Int", type: "hint" },
  { name: "Advanced", shortName: "Adv", type: "adv" },
  { name: "Bunny", shortName: "Bunny", type: "bny" },
  { name: "Let's Begin", shortName: "LB", type: "lb" },
  { name: "Let's Go 1", shortName: "LG1", type: "lg1" },
  { name: "Let's Go 2", shortName: "LG2", type: "lg2" },
  { name: "Let's Go 3", shortName: "LG3", type: "lg3" },
  { name: "Let's Go 4", shortName: "LG4", type: "lg4" },
  { name: "Let's Go 5", shortName: "LG5", type: "lg5" },
  { name: "Connect 1", shortName: "Conn 1", type: "ct1" },
  { name: "Connect 2", shortName: "Conn 2", type: "ct2" },
  { name: "Connect 3", shortName: "Conn 3", type: "ct3" },
  { name: "Private", shortName: "Pvt", type: "pvt" },
  { name: "Premium", shortName: "Prem", type: "prm" },
  { name: "High School", shortName: "HS", type: "hs" },
  { name: "Company", shortName: "Comp", type: "comp" },
  { name: "Other", shortName: "Other", type: "other" },
];
