export default [
  { label: "Grapeseed", shortName: "GS", value: "gs", bgColor: "#70428b" },
  { label: "Beginner", shortName: "Beg", value: "beg", bgColor: "#8ad2f3" },
  { label: "Elementary", shortName: "El", value: "el", bgColor: "#8ad2f3" },
  {
    label: "Low Intermediate",
    shortName: "L-Int",
    value: "lint",
    bgColor: "#8ad2f3",
  },
  {
    label: "High Intermediate",
    shortName: "H-Int",
    value: "hint",
    bgColor: "#8ad2f3",
  },
  { label: "Advanced", shortName: "Adv", value: "adv", bgColor: "#8ad2f3" },
  { label: "Bunny", shortName: "Bunny", value: "bny", bgColor: "#f7ae41" },
  { label: "Let's Begin", shortName: "LB", value: "lb", bgColor: "#f7ae41" },
  { label: "Let's Go 1", shortName: "LG1", value: "lg1", bgColor: "#f7ae41" },
  { label: "Let's Go 2", shortName: "LG2", value: "lg2", bgColor: "#f7ae41" },
  { label: "Let's Go 3", shortName: "LG3", value: "lg3", bgColor: "#f7ae41" },
  { label: "Let's Go 4", shortName: "LG4", value: "lg4", bgColor: "#f7ae41" },
  { label: "Let's Go 5", shortName: "LG5", value: "lg5", bgColor: "#f7ae41" },
  { label: "Connect 1", shortName: "Conn 1", value: "ct1", bgColor: "#f7ae41" },
  { label: "Connect 2", shortName: "Conn 2", value: "ct2", bgColor: "#f7ae41" },
  { label: "Connect 3", shortName: "Conn 3", value: "ct3", bgColor: "#f7ae41" },
  { label: "Private", shortName: "Pvt", value: "pvt", bgColor: "#8ad2f3" },
  { label: "Premium", shortName: "Prem", value: "prm", bgColor: "#7e2118" },
  { label: "High School", shortName: "HS", value: "hs", bgColor: "#7684c1" },
  { label: "Company", shortName: "Comp", value: "comp", bgColor: "#62a1d7" },
  {
    label: "Travel Time",
    shortName: "Trvl",
    value: "trav",
    bgColor: "#68728e",
  },
  { label: "Other", shortName: "Other", value: "other", bgColor: "#5fb98b" },
];
