export default [
  { name: "Grapeseed", shortName: "GS", type: "gs", bgColor: "#70428b" },
  { name: "Beginner", shortName: "Beg", type: "beg", bgColor: "#8ad2f3" },
  { name: "Elementary", shortName: "El", type: "el", bgColor: "#8ad2f3" },
  {
    name: "Low Intermediate",
    shortName: "L-Int",
    type: "lint",
    bgColor: "#8ad2f3",
  },
  {
    name: "High Intermediate",
    shortName: "H-Int",
    type: "hint",
    bgColor: "#8ad2f3",
  },
  { name: "Advanced", shortName: "Adv", type: "adv", bgColor: "#8ad2f3" },
  { name: "Bunny", shortName: "Bunny", type: "bny", bgColor: "#f7ae41" },
  { name: "Let's Begin", shortName: "LB", type: "lb", bgColor: "#f7ae41" },
  { name: "Let's Go 1", shortName: "LG1", type: "lg1", bgColor: "#f7ae41" },
  { name: "Let's Go 2", shortName: "LG2", type: "lg2", bgColor: "#f7ae41" },
  { name: "Let's Go 3", shortName: "LG3", type: "lg3", bgColor: "#f7ae41" },
  { name: "Let's Go 4", shortName: "LG4", type: "lg4", bgColor: "#f7ae41" },
  { name: "Let's Go 5", shortName: "LG5", type: "lg5", bgColor: "#f7ae41" },
  { name: "Connect 1", shortName: "Conn 1", type: "ct1", bgColor: "#f7ae41" },
  { name: "Connect 2", shortName: "Conn 2", type: "ct2", bgColor: "#f7ae41" },
  { name: "Connect 3", shortName: "Conn 3", type: "ct3", bgColor: "#f7ae41" },
  { name: "Private", shortName: "Pvt", type: "pvt", bgColor: "#8ad2f3" },
  { name: "Premium", shortName: "Prem", type: "prm", bgColor: "#7e2118" },
  { name: "High School", shortName: "HS", type: "hs", bgColor: "#7684c1" },
  { name: "Company", shortName: "Comp", type: "comp", bgColor: "#62a1d7" },
  { name: "Travel Time", shortName: "Trvl", type: "trav", bgColor: "#68728e" },
  { name: "Other", shortName: "Other", type: "other", bgColor: "#5fb98b" },
];
